version: "3"
services:
    app:
        build: .
        # command: tail -F anything
        command: flask run --host=0.0.0.0
        volumes: 
            - .:/usr/src/app
        ports:
            - 5000:5000
